os: osx
osx_image: xcode11.2
language: swift
script: xcodebuild clean build test -project QuizMobileApp/QuizMobileApp.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
